import { chromium } from "playwright";
const base = "http://localhost:3000";
const out = "/tmp/claude-0/-home-user-pixfortech/b9fe4a5d-cca4-5894-8a93-ccba0580142b/scratchpad/shots/v4";
const browser = await chromium.launch({ executablePath: "/opt/pw-browsers/chromium-1194/chrome-linux/chrome", args: ["--no-sandbox"] });
const ctx = await browser.newContext({ viewport: { width: 1366, height: 900 } });
const page = await ctx.newPage();
const errors = [];
page.on("console", (m) => { if (m.type() === "error") errors.push(m.text().slice(0, 200)); });
page.on("pageerror", (e) => errors.push("pageerror: " + e.message));
for (const p of ["/about", "/process", "/careers", "/contact"]) {
  await page.goto(base + p, { waitUntil: "load", timeout: 120000 });
  await page.waitForTimeout(1200);
  await page.screenshot({ path: `${out}/scene-${p.slice(1)}.png` });
}
// hero interaction: hover, click, drag, keyboard
await page.goto(base + "/", { waitUntil: "load", timeout: 120000 });
await page.waitForTimeout(3500);
const heroEvents = [];
await page.exposeFunction("__heroEvent", (k) => heroEvents.push(k));
await page.evaluate(() => window.addEventListener("pf:hero", (e) => window.__heroEvent(e.detail.kind)));
const scene = page.getByTestId("hero-scene");
const box = await scene.boundingBox();
await page.mouse.move(box.x + box.width * 0.75, box.y + box.height * 0.5, { steps: 12 });
await page.waitForTimeout(300);
await page.mouse.click(box.x + box.width * 0.72, box.y + box.height * 0.55);
await page.waitForTimeout(200);
await page.screenshot({ path: `${out}/hero-pulse.png` });
await page.mouse.move(box.x + box.width * 0.7, box.y + box.height * 0.5);
await page.mouse.down();
await page.mouse.move(box.x + box.width * 0.55, box.y + box.height * 0.35, { steps: 15 });
await page.waitForTimeout(150);
await page.screenshot({ path: `${out}/hero-drag.png` });
await page.mouse.up();
await scene.focus();
await page.keyboard.press("Enter");
await page.waitForTimeout(300);
console.log("hero events:", heroEvents);
await page.goto(base + "/login", { waitUntil: "load", timeout: 120000 });
await page.getByLabel("Email").fill("pm@pixelforge.test");
await page.getByLabel("Password").fill("forge-demo-2026!");
await page.getByRole("button", { name: "Sign in" }).click();
await page.waitForURL(/admin/, { timeout: 30000 });
await page.waitForTimeout(2500);
await page.screenshot({ path: `${out}/admin-dashboard.png`, fullPage: true });
await page.getByTestId("bell").click();
await page.waitForTimeout(400);
await page.screenshot({ path: `${out}/admin-bell.png` });
console.log("ERRORS:", errors.length ? errors : "none");
await browser.close();
