import { chromium } from "playwright";
const base = "http://localhost:3000";
const out = "/tmp/claude-0/-home-user-pixfortech/b9fe4a5d-cca4-5894-8a93-ccba0580142b/scratchpad/shots/v4";
const browser = await chromium.launch({ executablePath: "/opt/pw-browsers/chromium-1194/chrome-linux/chrome", args: ["--no-sandbox"] });
const ctx = await browser.newContext({ viewport: { width: 1366, height: 900 } });
const page = await ctx.newPage();
const errors = [];
page.on("console", (m) => { if (m.type() === "error") errors.push(m.text().slice(0, 300)); });
page.on("pageerror", (e) => errors.push("pageerror: " + e.message));
await page.goto(base + "/", { waitUntil: "load", timeout: 120000 });
await page.waitForTimeout(1500);
console.log("login link:", await page.getByTestId("login-link").count());
await page.screenshot({ path: `${out}/home-header.png` });
await page.goto(base + "/people", { waitUntil: "load", timeout: 120000 });
await page.screenshot({ path: `${out}/people.png` });
await page.goto(base + "/login", { waitUntil: "load", timeout: 120000 });
await page.getByLabel("Email").fill("admin@pixelforge.test");
await page.getByLabel("Password").fill("forge-demo-2026!");
await page.getByRole("button", { name: "Sign in" }).click();
await page.waitForURL(/admin/, { timeout: 30000 });
await page.goto(base + "/admin/profile", { waitUntil: "load", timeout: 120000 });
await page.waitForTimeout(1000);
await page.screenshot({ path: `${out}/admin-profile.png`, fullPage: true });
console.log("username input:", await page.getByTestId("username-input").inputValue(), "slug:", await page.getByTestId("slug-input").inputValue());
await page.goto(base + "/", { waitUntil: "load", timeout: 120000 });
await page.waitForTimeout(1500);
console.log("account button:", await page.getByTestId("account-button").count());
await page.getByTestId("account-button").click();
await page.waitForTimeout(300);
await page.screenshot({ path: `${out}/home-account-menu.png` });
console.log("ERRORS:", errors.length ? errors : "none");
await browser.close();
